### PR TITLE
Update rocoto generation for new stage_ic and add GEFS

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
# Description
The structure of staged ICs have been updated to be more streamlined and also to allow ensemble members to support GEFS. The data dependencies for the job are updated to use the new file structure. The location on Hera is updated to a temporary directory with the new structure for testing.

The stage_ic job is also added to the GEFS job mesh to copy staged initial conditions. The GEFS stage_ic job currently only checks that the mem000 files exist before beginning (any missing members will not pop up until the job runs).

Refs NOAA-EMC/global-workflow#911

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES
- Does this change require a documentation update? NO

# How has this been tested?
Workflow generation on Hera

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
I tested and the rocoto aspects work correctly with these changes. The stage_ic job is failing, but that will be up to you to diagnose and correct.

**Comment by AnilKumar-NOAA** [comment]
> I tested and the rocoto aspects work correctly with these changes. The stage_ic job is failing, but that will be up to you to diagnose and correct.

will check stage_ic and test

**Review by AnilKumar-NOAA — COMMENTED** [review]
updated these changes.

**Comment by AnilKumar-NOAA** [comment]
> I tested and the rocoto aspects work correctly with these changes. The stage_ic job is failing, but that will be up to you to diagnose and correct.

Updated all changes. Will work on why stage_ic job failing. Thanks Walter!

**Comment by WalterKolczynski-NOAA** [comment]
Did you copy these changes by hand again? Why not just merge the PR?

**Comment by AnilKumar-NOAA** [comment]
> Did you copy these changes by hand again? Why not just merge the PR?

Yes, I should have merge this PR directly. I did manually to understand each files and staging process.

**Comment by AnilKumar-NOAA** [comment]
Merged PR 
Now work on why stage_ic job failing

**Pull request merged**
